cosmicds/tempo-lite

- src/TempoLite.vue
- src/main.ts
More updates to bring UI in line with Alyssa's mockup:
- add scenario header
- remove unneeded buttons
Also add checkbox option to turn off field of regard.
The control box is not well styled yet. We talked about a few different options with Alyssa, including having the settings gear be in the upper right and then push in as a full side panel from the right, but that might be overkill right now for 1 option; so might be fine to just have a plain checkbox for the FoR under the list of scenarios.
> UI updates

- src/LocationSearch.vue
- src/TempoLite.vue
- Make search box text larger
- Add text to TEMPO info blurb
- Add logos
> UI updates 2

- src/TempoLite.vue
This PR sets up a basic skeleton for adding location-of-interest buttons based on the day. @patudom will add in the actual interesting location content.
> Location of interest buttons

- src/TempoLite.vue
@johnarban, you were right. Alyssa didn't like the autoplay. :)
> don't autoplay for location buttons and start where there is data

- src/InfoButton.vue
- src/TempoLite.vue
- src/main.ts
This implements the intro requested by Erika and Mary and updates the title of the page and the locations of interest.
I wasn't sure how to add the info buttons within the radio groups, so I haven't done those yet. @johnarban, would you be able to take a look at this, please?
> Add new intro and update titles for story and locations of interest

- src/TempoLite.vue
Add `?hideintro=true` url parameter to hide the intro slide at startup
> add query parameter

- src/TempoLite.vue
This PR allows changing the opacity of the image overlay using a slider.
> Allow changing image opacity

- src/TempoLite.vue
> make pixels crispy

- src/InfoButton.vue
- src/TempoLite.vue
> minor updates

- src/TempoLite.vue
This PR changes the starting opacity of the image overlay back to 1.
> Change starting opacity to be 1

- src/TempoLite.vue
Changes the label of the time zone depending on if it currently DST or Standard time
> handle DST timezone in label

- src/TempoLite.vue
Update map tile layer to use stamen toner style
> Change-map-tile-layer

- src/TempoLite.vue
Redo the changes from #70 now that we have Stadia authentication set up.
> Redo map layer update

- src/TempoLite.vue
This is a tiny PR that fixes the index for the featured event dates.
> Fix featured events date label

- src/LocationSearch.vue
- src/TempoLite.vue
These are some very small UI updates to address feedback from educators & scientists:
- Let location search zoom in closer to location
- Change text in location search box to clarify that you can't enter an address
- Clarify what opacity slider refers to
- Don't show clouds by default
> UI updates 4

- src/TempoLite.vue
remove whichdataset label left over from debug
> remove whichdataset label

- src/TempoLite.vue
- Change map controls button styling to look more like the leaflet map controls
- Add x button to close card
- Change order of controls
- Give card a bit of a border
> update map controls button and card styling

- src/TempoLite.vue
maintain the pathname for the location sharing
> Add the pathname

- src/TempoLite.vue
Fix #63 by adding a maker for searched for location
> add marker for searched for location

- .github/workflows/build-deploy.yml
- src/TempoLite.vue
Tracks the custom venue url. Will only `POST` if `venue` is in the URL and hasn't been seen before
**TODO**: Needs API endpiont
> Track custom venue url

- src/TempoLite.vue
Fix switching to the 0th event.
> Bug Fix: switching to 0th event
